export const apartment = [
  {
    id: "1",
    title: "Luxury Loft",
    descr: "Spacious loft with modern decor and stunning views. ",
    price: 2500,
    rating: 4,
    photo: "../img/apartments/apartment-1.jpg",
    location: { city: "New York City" },
    owner: {
      name: "John Smith",
      phone: "555-555-5555",
      email: "john.smith@example.com",
    },
  },
  {
    id: "2",
    title: "Beachside Bungalow",
    descr:
      "Located in the heart of downtown, this spacious apartment offers stunning views of the city skyline. ",
    price: 1200,
    rating: 3,
    photo: "../img/apartments/apartment-2.jpg",
    location: { city: "Miami" },
    owner: {
      name: "Jane Doe",
      phone: "555-555-5555",
      email: "jane.doe@example.com",
    },
  },
  {
    id: "3",
    title: "Modern Studio",
    descr: "Sleek and stylish studio in the heart of the city",
    price: 1800,
    rating: 5,
    photo: "../img/apartments/apartment-3.jpg",
    location: { city: "Los Angeles" },
    owner: {
      name: "Bob Johnson",
      phone: "555-555-5555",
      email: "bob.johnson@example.com",
    },
  },
  {
    id: "4",
    title: "Charming Cottage",
    descr: "Quaint cottage with vintage charm and cozy atmosphere",
    price: 1500,
    rating: 4,
    photo: "../img/apartments/apartment-4.jpg",
    location: { city: "Seattle" },
    owner: {
      name: "Mary Smith",
      phone: "555-555-5555",
      email: "mary.smith@example.com",
    },
  },
  {
    id: "5",
    title: "Industrial Loft",
    descr: "Stylish loft with industrial-inspired design",
    price: 2200,
    rating: 4,
    photo: "../img/apartments/apartment-5.jpg",
    location: { city: "Chicago" },
    owner: {
      name: "Mike Johnson",
      phone: "555-555-5555",
      email: "mike.johnson@example.com",
    },
  },
  {
    id: "6",
    title: "Penthouse Suite",
    descr: "Luxurious penthouse with panoramic views of the city",
    price: 5000,
    rating: 5,
    photo: "../img/apartments/apartment-6.jpg",
    location: { city: "San Francisco" },
    owner: {
      name: "Emily Davis",
      phone: "555-555-5555",
      email: "emily.davis@example.com",
    },
  },
  {
    id: "7",
    title: "Cozy Studio",
    descr: "Comfortable studio with warm and welcoming atmosphere",
    price: 1000,
    rating: 3,
    photo: "../img/apartments/apartment-7.jpg",
    location: { city: "Boston" },
    owner: {
      name: "Tom Brown",
      phone: "555-555-5555",
      email: "tom.brown@example.com",
    },
  },
  {
    id: "8",
    title: "Sunny Apartment",
    descr: "Bright and sunny apartment with modern furnishings",
    price: 1900,
    rating: 4,
    photo: "../img/apartments/apartment-8.jpg",
    location: { city: "Denver" },
    owner: {
      name: "Sarah Johnson",
      phone: "555-555-5555",
      email: "sarah.johnson@example.com",
    },
  },
  {
    id: "9",
    title: "Historic Townhouse",
    descr: "Elegant townhouse with historic charm and refined style",
    price: 3500,
    rating: 5,
    photo: "../img/apartments/apartment-9.jpg",
    location: { city: "Washington D.C." },
    owner: {
      name: "David Lee",
      phone: "555-555-5555",
      email: "david.lee@example.com",
    },
  },
  {
    id: "10",
    title: "Contemporary Condo",
    descr:
      "Sophisticated condo with contemporary design and luxurious amenities",
    price: 4200,
    rating: 5,
    photo: "../img/apartments/apartment-10.jpg",
    location: { city: "Toronto" },
    owner: {
      name: "Julia Rodriguez",
      phone: "555-555-5555",
      email: "julia.rodriguez@example.com",
    },
  },
];
